#define REQUIRED_ARGS \
    REQUIRED_STRING_ARG(source_file, "source", "Source .c file path") \
    REQUIRED_STRING_ARG(header_file, "header", "Header .h file path") \

#define BOOLEAN_ARGS \
    BOOLEAN_ARG(help, "-h", "Show help") \
    BOOLEAN_ARG(debug, "-d", "Print debug messages into stderr")

#include <assert.h>
#include <stdbool.h>

#include "easy-args/includes/easyargs.h"

#define MAX_PUBLIC_FUNCTIONS 128
#define MAX_LINE_LENGTH 1024
#define HEADER_SECTION_START_PATTERN "// HEADER DECLARATIONS AUTOGENERATED FROM"
#define HEADER_SECTION_END_PATTERN "// END OF HEADER DECLARATIONS AUTOGENERATED FROM"

#define STRUCT(name) typedef struct name name; struct name

STRUCT(string) {
    char* buffer;
    int length;
    int capacity;
};

string new_string(int capacity) {
    string str = {
        .buffer = malloc(capacity),
        .length = 0,
        .capacity = capacity,
    };
    assert(str.buffer != NULL);
    return str;
}

void free_string(string str) {
    free(str.buffer);
}

void print_string(FILE* file, string str) {
    for (int i = 0; i < str.length; i++) {
        fprintf(file, "%c", str.buffer[i]);
    }
}

string append(string str, char c) {
    assert(str.length < str.capacity);
    str.buffer[str.length] = c;
    str.length++;
    return str;
}

string trim_trailing_character(string str, char c) {
    while (str.length > 0 && str.buffer[str.length - 1] == c) {
        str.length--;
    }
    return str;
}

// Returns whether the pattern matched or not
bool drop_pattern(string* str, char* pattern) {
    int len = strlen(pattern);
    while (str->length > 0 && len > 0) {
        if (str->buffer[str->length - 1] == pattern[len - 1]) {
            str->length--;
            len--;
        } else {
            return false;
        }
    }
    return len == 0;
}

bool drop_front_pattern(string* str, char* pattern) {
    int len = strlen(pattern);
    for (int i = 0; i < len; i++) {
        if (i >= str->length || str->buffer[i] != pattern[i]) {
            return false;
        }
    }
    for (int i = 0; i < str->length - len; i++) {
        str->buffer[i] = str->buffer[i + len];
    }
    str->length -= len;
    return true;
}

bool starts_with(string str, char* pattern) {
    for (int i = 0; pattern[i] != 0; i++) {
        if (i >= str.length || str.buffer[i] != pattern[i]) {
            return false;
        }
    }
    return true;
}

string fgetline(FILE* stream) {
    string line_buffer = new_string(MAX_LINE_LENGTH);
    while (true) {
        char c = fgetc(stream);
        if (c == EOF) {
            break;
        }
        line_buffer = append(line_buffer, c);
        if (c == '\n') {
            break;
        }
    }
    if (line_buffer.length == 0) {
        free_string(line_buffer);
        return (string) { 0 };
    }
    return line_buffer;
}

int main(int argc, char* argv[]) {
    args_t args = make_default_args();

    if (!parse_args(argc, argv, &args) || args.help) {
        print_help(argv[0]);
        return 1;
    }

    if (args.debug) {
        fprintf(stderr, "Adding public functions from %s to %s\n", args.source_file, args.header_file);
    }

    FILE* source_file = fopen(args.source_file, "r");
    FILE* header_file = fopen(args.header_file, "rw");

    if (source_file == NULL) {
        fprintf(stderr, "Error opening source file %s\n", args.source_file);
    }
    if (header_file == NULL) {
        fprintf(stderr, "Error opening header file %s\n", args.header_file);
    }

    int num_of_declarations = 0;
    string declarations[MAX_PUBLIC_FUNCTIONS];
    while (true) {
        string line = fgetline(source_file);
        if (line.length == 0) {
            break;
        }
        if (drop_front_pattern(&line, "PUBLIC ")) {
            assert(num_of_declarations < MAX_PUBLIC_FUNCTIONS);
            line = trim_trailing_character(line, '\n');
            line = trim_trailing_character(line, ' ');
            line = trim_trailing_character(line, '{');
            line = trim_trailing_character(line, ' ');
            line = append(line, ';');
            declarations[num_of_declarations] = line;
            num_of_declarations++;
            if (args.debug) {
                fprintf(stderr, "Saved declaration: \"");
                print_string(stderr, line);
                fprintf(stderr, "\"\n");
            }
        } else {
            free_string(line);
        }
    }

    long section_start = -1;
    long section_end = -1;
    while (true) {
        int line_start = ftell(header_file);
        string line = fgetline(header_file);
        int line_end = ftell(header_file);
        if (line.length == 0) {
            break;
        }
        line = trim_trailing_character(line, '\n');
        line = trim_trailing_character(line, ' ');
        if (section_start == -1) {
            // Try to match against "HEADER DECLARATIONS AUTOGENERATED FROM source.c"
            bool matched_begin = true;
            matched_begin &= drop_pattern(&line, args.source_file);
            line = trim_trailing_character(line, ' ');
            matched_begin &= drop_pattern(&line, HEADER_SECTION_START_PATTERN);
            if (matched_begin) {
                section_start = line_start;
            }
        } else {
            // Try to match against "END OF HEADER DECLARATIONS AUTOGENERATED FROM source.c"
            bool matched_end = true;
            matched_end &= drop_pattern(&line, args.source_file);
            line = trim_trailing_character(line, ' ');
            matched_end &= drop_pattern(&line, HEADER_SECTION_END_PATTERN);
            if (matched_end) {
                section_end = line_end;
            }
        }
    }

    if (section_start == -1) {
        fprintf(stderr, "Could not find the start of the section, please include the following line in your header\n");
        fprintf(stderr, "%s %s\n", HEADER_SECTION_START_PATTERN, args.source_file);
    }
    if (section_end == -1) {
        fprintf(stderr, "Could not find the start of the section, please include the following line in your header\n");
        fprintf(stderr, "%s %s\n", HEADER_SECTION_END_PATTERN, args.source_file);
    }
    if (section_start == -1 || section_end == -1) {
        return 1;
    }

    fseek(header_file, 0, SEEK_SET);
    for (int i = 0; i < section_start; i++) {
        int c = fgetc(header_file);
        assert(c != EOF);
        fputc(c, stdout);
    }
    printf( "%s %s\n", HEADER_SECTION_START_PATTERN, args.source_file);
    for (int i = 0; i < num_of_declarations; i++) {
        print_string(stdout, declarations[i]);
        printf("\n");
    }
    printf("%s %s\n", HEADER_SECTION_END_PATTERN, args.source_file);
    fseek(header_file, section_end, SEEK_SET);
    for (int c; (c = fgetc(header_file)) != EOF; ) {
        fputc(c, stdout);
    }

    return 0;
}
