struct a_struct_definition {
    int length;
};

// HEADER DECLARATIONS AUTOGENERATED FROM ./test/source.c
int this_is_a_function(void);a sdfasdf ads
// END OF HEADER DECLARATIONS AUTOGENERATED FROM ./test/source.c
